// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9eMO-X442niY80M_yceGqusgn3TJ4BIY',
    appId: '1:409468177523:android:af48ef4fd2301b88212e06',
    messagingSenderId: '409468177523',
    projectId: 'scheduleforictis',
    databaseURL: 'https://scheduleforictis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scheduleforictis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL4mECXglz6FGFokUv6w6yGivZgnWovh8',
    appId: '1:409468177523:ios:7224f0d0ade31e43212e06',
    messagingSenderId: '409468177523',
    projectId: 'scheduleforictis',
    databaseURL: 'https://scheduleforictis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scheduleforictis.appspot.com',
    iosBundleId: 'com.example.scheduleForIctisFlutter',
  );

}