@startuml

class РасписаниеНаНеделю
class РасписаниеНаДень

class Событие
class УчебноеЗанятие
class Мероприятие

class Задание
class СубъектРасписания

class Напоминание
class Файл

class Пользователь

Пользователь o-- СубъектРасписания

СубъектРасписания o-- РасписаниеНаНеделю
РасписаниеНаНеделю o-- РасписаниеНаДень
РасписаниеНаДень o-- Событие
Событие <|-- УчебноеЗанятие
Событие <|-- Мероприятие

УчебноеЗанятие o-- Задание
Мероприятие o-- Напоминание
Задание o-- Напоминание
Задание o-- Файл

@enduml